services:
  # Frontend Service
  - type: web
    name: dashboard-aguas-ancud-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l $PORT
    rootDir: .
    envVars:
      - key: VITE_API_URL
        value: https://dashboard-aguas-ancud-backend.onrender.com
      - key: NODE_ENV
        value: production 